name: Android CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
          
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          bash ./gradlew assembleRelease
          bash ./gradlew assembleDebug

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: StatusBarLyric_release
          path: ${{ steps.sign_release.outputs.signedReleaseFile }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: StatusBarLyric_debug
          path: ${{ steps.sign_debug.outputs.signedReleaseFile }}

      - name: Upload Release Mapping
        uses: actions/upload-artifact@v2
        with:
          name: StatusBarLyric_release_mapping
          path: ./app/build/outputs/mapping/release/mapping.txt
